import os
from typing import Dict, Any

PRE_COMMIT_SCRIPT = """#!/bin/sh
# Auto-generated by dotvet pre-commit hook
echo "🛡️ Running dotvet security gate before commit..."

if command -v dotvet >/dev/null 2>&1; then
  dotvet check --strict
  STATUS=$?
elif command -v npx >/dev/null 2>&1; then
  npx dotvet check --strict
  STATUS=$?
else
  echo "⚠️ dotvet not found in PATH, skipping pre-commit env audit."
  STATUS=0
fi

if [ $STATUS -ne 0 ]; then
  echo "❌ dotvet detected environment/secret security violations! Commit rejected."
  echo "💡 Run 'dotvet fix' or 'npx dotvet fix' to auto-repair."
  exit 1
fi
"""

PRE_PUSH_SCRIPT = """#!/bin/sh
# Auto-generated by dotvet pre-push hook
echo "🛡️ Running dotvet pre-push firewall check..."

# Force push lock: prevent accidental force pushes to protected branches (main / master)
z40="0000000000000000000000000000000000000000"
while read -r local_ref local_sha remote_ref remote_sha; do
  if [ "$remote_ref" = "refs/heads/main" ] || [ "$remote_ref" = "refs/heads/master" ]; then
    if [ "$local_sha" != "$z40" ] && [ "$remote_sha" != "$z40" ]; then
      if ! git merge-base --is-ancestor "$remote_sha" "$local_sha" 2>/dev/null; then
        echo "❌ dotvet blocked force-push to protected branch ($remote_ref)!"
        echo "🔒 Force push locks are enabled to protect repository history."
        exit 1
      fi
    fi
  fi
done

if command -v dotvet >/dev/null 2>&1; then
  dotvet check --strict
  STATUS=$?
elif command -v npx >/dev/null 2>&1; then
  npx dotvet check --strict
  STATUS=$?
else
  echo "⚠️ dotvet not found in PATH, skipping pre-push env audit."
  STATUS=0
fi

if [ $STATUS -ne 0 ]; then
  echo "❌ dotvet blocked git push! Insecure environment configurations or historical leaks detected."
  echo "💡 Run 'dotvet check' to inspect issues."
  exit 1
fi
"""


def install_git_hook(root_dir: str = ".") -> Dict[str, Any]:
    git_dir = os.path.join(root_dir, ".git")
    if not os.path.exists(git_dir):
        return {"ok": False, "error": "Not a git repository (.git folder not found)."}

    hooks_dir = os.path.join(git_dir, "hooks")
    os.makedirs(hooks_dir, exist_ok=True)

    pre_commit_file = os.path.join(hooks_dir, "pre-commit")
    with open(pre_commit_file, "w", encoding="utf-8") as f:
        f.write(PRE_COMMIT_SCRIPT)

    pre_push_file = os.path.join(hooks_dir, "pre-push")
    with open(pre_push_file, "w", encoding="utf-8") as f:
        f.write(PRE_PUSH_SCRIPT)

    try:
        os.chmod(pre_commit_file, 0o755)
        os.chmod(pre_push_file, 0o755)
    except Exception:
        pass

    return {
        "ok": True,
        "preCommitPath": pre_commit_file,
        "prePushPath": pre_push_file,
        "hookPath": pre_commit_file,
    }

